ayomidescrumy/urls.py
from django.urls import path, include
from . import views

app_name = 'ayomidescrumy'
urlpatterns = [
    path('', views.index, name='about'),
    path('addgoal', views.add_goal, name='addgoal'),
    path('home/', views.home, name='home'),
    path('changegroup/', views.change_goal, name='change_goal'),
    path('movegoal/<int:goal_id>/', views.move_goal, name="movegoal"),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
]

django-ayomidescrumy/ayomidescrumy/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'ayomidescrumy'
urlpatterns = [
    path('', views.index, name='index'),
    path('addgoal', views.add_goal, name='addgoal'),
    path('home', views.home, name='home'),
    path('movegoal/<int:goal_id>/', views.move_goal, name="movegoal"),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('charlesmaryayoscrumy/', include('ayomidescrumy.urls', namespace='ayomidescrumy'))
]

ayomidescrumy/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User, Group
from .models import ScrumyGoals, GoalStatus
from django import forms


class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    # goal_status = GoalStatus.objects.all()
    # goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in goal_status.order_by('id')[0:1]])
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name']


class DeveloperChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:3]])

    class Meta():
        model = GoalStatus
        fields = ['goal_status']


class QAChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[1:4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class QAChangeGoalForm1(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[2:4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class OwnerChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[:4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class AdminChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[:4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


#create goal form

class DeveloprCreateGoalForm(forms.ModelForm):
    # goal_status = GoalStatus.objects.all()
    # goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in goal_status.order_by('id')[0:1]])
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name']

class QACreateGoalForm(forms.ModelForm):
    # goal_status = GoalStatus.objects.all()
    # goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in goal_status.order_by('id')[0:1]])
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name']

class OwnerCreateGoalForm(forms.ModelForm):
    # goal_status = GoalStatus.objects.all()
    # goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in goal_status.order_by('id')[0:1]])
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name']

class ChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class ChangeGroup(forms.ModelForm):
    queryset = Group.objects.all()
    groups = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:4]])

    class Meta():
        model = Group
        fields = ['groups']

django-ayomidescrumy/ayomidescrumy/forms.py
from django.forms import ModelForm, TextInput
from django.contrib.auth.models import User
from .models import ScrumyGoals


class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']

ayomidescrumy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import ScrumyGoals, GoalStatus
from django.contrib.auth.models import User, Group, auth
from django.contrib.auth import get_user_model, login, authenticate
from .forms import *
import random
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages


def index(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name,
                                            last_name=last_name)
            user.save()

            new_user = User.objects.get(username=username)
            group = Group.objects.get(name='Developer')
            group.user_set.add(new_user)

            messages.success(request, f'Your account has been created successfully!')

            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('/ayomidescrumy/home')
            else:
                return redirect('/ayomidescrumy/accounts/login')

    else:
        form = SignupForm()

    context = {'form': form}

    return render(request, 'ayomidescrumy/index.html', context)


# Create your views here.
def move_goal(request, goal_id):
    try:
        goals = ScrumyGoals.objects.get(goal_id=goal_id)
    except ObjectDoesNotExist:
        dictionary = {
            'error': 'A record with that goal id does not exist'
        }
        return render(request, 'ayomidescrumy/exception.html', dictionary)
    else:
        current_user = request.user
        usr_grp = request.user.groups.all()[0]
        if usr_grp == Group.objects.get(name='Developer') and current_user == goals.user:
            if request.method == 'POST':
                form = DeveloperChangeGoalForm(request.POST)
                if form.is_valid():
                    selected_status = form.save(commit=False)
                    selected = form.cleaned_data['goal_status']
                    choice = GoalStatus.objects.get(id=int(selected))
                    goals.goal_status = choice
                    goals.save()
                    return redirect("/ayomidescrumy/home")
                else:
                    return HttpResponse('You are not permitted to move goal to Done Status')
            else:
                form = DeveloperChangeGoalForm()

        elif usr_grp == Group.objects.get(name='Quality Assurance') and current_user == goals.user:
            if request.method == 'POST':
                form = QAChangeGoalForm(request.POST)
                if form.is_valid():
                    selected_status = form.save(commit=False)
                    selected = form.cleaned_data['goal_status']
                    choice = GoalStatus.objects.get(id=int(selected))

                    goals.goal_status = choice

                    goals.save()
                    return redirect("/ayomidescrumy/home")
                else:
                    return HttpResponse('Quality Assurance user can not move goals to weekly goals')

            else:
                form = QAChangeGoalForm()
        elif usr_grp == Group.objects.get(name='Quality Assurance') and current_user != goals.user:
            if goals.goal_status == 'Weekly Goal' or 'Daily Goal':
                return HttpResponse("You are only permitted to move other user's goal status from Verify status to "
                                        "Done Status")
            if request.method == 'POST':
                form = QAChangeGoalForm1(request.POST)
                if form.is_valid():
                    selected_status = form.save(commit=False)
                    selected = form.cleaned_data['goal_status']
                    choice = GoalStatus.objects.get(id=int(selected))
                    goals.goal_status = choice
                    goals.save()
                    return redirect("/ayomidescrumy/home")
                else:
                    return HttpResponse("You are only permitted to move other user's goal status from Verify status to "
                                        "Done Status")
            form = QAChangeGoalForm1()
        elif usr_grp == Group.objects.get(name='Owner') and current_user == goals.user:
            if request.method == 'POST':
                form = OwnerChangeGoalForm(request.POST)
                if form.is_valid():
                    selected_status = form.save(commit=False)
                    selected = form.cleaned_data['goal_status']
                    choice = GoalStatus.objects.get(id=int(selected))
                    goals.goal_status = choice
                    goals.save()
                    return redirect("/ayomidescrumy/home")
            form = OwnerChangeGoalForm()

        elif usr_grp == Group.objects.get(name='Owner') and current_user != goals.user:
            if request.method == 'POST':
                form = OwnerChangeGoalForm(request.POST)
                if form.is_valid():
                    selected_status = form.save(commit=False)
                    selected = form.cleaned_data['goal_status']
                    choice = GoalStatus.objects.get(id=int(selected))
                    goals.goal_status = choice
                    goals.save()
                    return redirect("/ayomidescrumy/home")
            form = OwnerChangeGoalForm()

        elif usr_grp == Group.objects.get(name='Admin'):
            if request.method == 'POST':
                form = AdminChangeGoalForm(request.POST)
                if form.is_valid():
                    selected_status = form.save(commit=False)
                    selected = form.cleaned_data['goal_status']
                    choice = GoalStatus.objects.get(id=int(selected))
                    goals.goal_status = choice
                    goals.save()
                    return redirect("/ayomidescrumy/home")
        else:
            return HttpResponse('You are not authorised to move this goal')
        form = AdminChangeGoalForm()
        return render(request, 'ayomidescrumy/moveGoal.html',
                      {'form': form, 'goals': goals, 'current_user': current_user, 'goal_name': goals.goal_name})


def add_goal(request):
    dev = User.objects.filter(groups__name__in=['Developer'])
    qa = User.objects.filter(groups__name__in=['Quality Assurance'])
    admin = User.objects.filter(groups__name__in=['Admin'])
    own = User.objects.filter(groups__name__in=['Owner'])
    if request.user in dev:
        form = DeveloprCreateGoalForm()
        dictionary = {'form': form, 'goal_status': GoalStatus.objects.get(status_name="Weekly Goal")}
        if request.method == 'POST':
            form = DeveloprCreateGoalForm(request.POST)
            if form.is_valid():
                user = User.objects.get(username=request.user.username)
                add_goal = ScrumyGoals()
                add_goal = form.save(commit=False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.created_by = user
                add_goal.moved_by = user
                add_goal.owner = user
                add_goal.user = user
                add_goal.goal_status = GoalStatus.objects.get(status_name="Weekly Goal")
                add_goal.save()
                return redirect("/ayomidescrumy/home")
            return HttpResponse("Invalid credentials provided, please fill out all fields")
        else:
            form = DeveloprCreateGoalForm()
            return render(request, 'ayomidescrumy/goal.html', dictionary)

    elif request.user in qa:
        form = QACreateGoalForm()
        dictionary = {'form': form, 'goal_status': GoalStatus.objects.get(status_name="Weekly Goal")}
        if request.method == 'POST':
            form = QACreateGoalForm(request.POST)
            if form.is_valid():
                user = User.objects.get(username=request.user.username)
                add_goal = ScrumyGoals()
                add_goal = form.save(commit=False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.created_by = user
                add_goal.moved_by = user
                add_goal.owner = user
                add_goal.user = user
                add_goal.goal_status = GoalStatus.objects.get(status_name="Weekly Goal")
                add_goal.save()
                return redirect("/ayomidescrumy/home")
            return HttpResponse("Invalid credentials provided, please fill out all fields")
        else:
            form = QACreateGoalForm()

        return render(request, 'ayomidescrumy/goal.html', dictionary)
    elif request.user in admin:
        form = CreateGoalForm()
        dictionary = {'form': form, 'goal_status': GoalStatus.objects.get(status_name="Weekly Goal")}

        if request.method == 'POST':
            form = CreateGoalForm(request.POST)
            if form.is_valid():
                user = User.objects.get(username=request.user.username)
                add_goal = ScrumyGoals()
                add_goal = form.save(commit=False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.created_by = user
                add_goal.moved_by = user
                add_goal.owner = user
                add_goal.user = user
                add_goal.goal_status = GoalStatus.objects.get(status_name="Weekly Goal")
                add_goal.save()
                return redirect("/ayomidescrumy/home")

django-ayomidescrumy/ayomidescrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import ScrumyGoals, GoalStatus
from django.contrib.auth.models import User, Group
from .forms import SignupForm, CreateGoalForm
import random


def index(request):
    # goal = ScrumyGoals.objects.filter(goal_name='Learn Django')
    # return HttpResponse(goal)

    form = SignupForm()

    if request.method == 'POST':
        form = SignupForm(request.POST)
        form.save()
        user = User.objects.get(username=request.POST['username'])
        my_group = Group.objects.get(name='Developer')
        my_group.user_set.add(user)

        if user.groups.filter(name='Developer').exists():
            return HttpResponse("Your account has been created successfully")

    elif request.method == 'GET':
        form = SignupForm()

    context = {'form': form}

    return render(request, 'ayomidescrumy/index.html', context)

    # return HttpResponse("This is a Scrum Application")


# Create your views here.
def move_goal(request, goal_id):
    try:
        goal = ScrumyGoals.objects.get(goal_id=goal_id)
    except Exception as e:
        dictionary = {
            'error': 'A record with that goal id does not exist'
        }
        return render(request, 'ayomidescrumy/exception.html', dictionary)
    else:
        return HttpResponse(goal.goal_name)


def add_goal(request):
    '''user = User.objects.first()
    random_number = random.randint(1000, 9999)
    weekly_goal = GoalStatus.objects.get(status_name='Weekly Goal')

    new_goal = ScrumyGoals(goal_name='Keep Learning Django', goal_id=random_number,
                           created_by='Louis', moved_by='Louis', owner='Louis', goal_status=weekly_goal, user=user)
    new_goal.save()
    return HttpResponse(new_goal)'''

    form = CreateGoalForm()
    if request.method == 'POST':
        form = CreateGoalForm(request.POST)
        form.save()

    elif request.method == 'GET':
        form = CreateGoalForm()

    context = {'form': form}

    return render(request, 'ayomidescrumy/goal.html', context)


def home(request):
    my_users = User.objects.all()
    my_first_user = my_users[0]
    my_goals = my_first_user.user.all()
    goal_status = GoalStatus.objects.all()
    weekly_goal = goal_status[0]
    daily_goal = goal_status[1]
    verify_goal = goal_status[2]
    done_goal = goal_status[3]

    dictionary = {
        'my_first_user': my_first_user,
        'weekly_goal': weekly_goal,
        'daily_goal': daily_goal,
        'verify_goal': verify_goal,
        'done_goal': done_goal,
        'my_goals': my_goals,
        'my_users': my_users,
    }

    return render(request, 'ayomidescrumy/home.html', dictionary)

ayomidescrumy/templates/ayomidescrumy/changeGroup.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Goal</title>
</head>
<body>
    <div class="container">
        {% if request.user.is_authenticated %}
		<a style="float: right;" href="/ayomidescrumy/accounts/logout" class="btn btn-primary m-3">Log Out</a>
		{%else%}
		<a style="float: right;" href="/ayomidescrumy/accounts/login" class="btn btn-primary m-3">Log IN</a>
		{% endif %}
        <p class="badge badge-danger m-3"> {{request.user.username}} is logged in </p>
		<p class="badge badge-danger m-3">Group: {{request.user.groups.all.0}}</p>
		
        <h1>Change Group</h1>
        <div class="row">
            <div class="col-md-4">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                <button type="submit" class="btn btn-primary mt-3">Change Group</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

ayomidescrumy/templates/ayomidescrumy/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Exception</title>
</head>
<body>
  {% if request.user.is_authenticated %}
		<a style="float: right;" href="/ayomidescrumy/accounts/logout" class="btn btn-primary m-3">Log Out</a>
		{%else%}
		<a style="float: right;" href="/ayomidescrumy/accounts/login" class="btn btn-primary m-3">Log IN</a>
		{% endif %}
   <p class="badge badge-danger m-3"> {{request.user.username}} is logged in </p>
		<p class="badge badge-danger m-3">Group: {{request.user.groups.all.0}}</p>
		
    <p>{{error}}</p>
</body>
</html>

ayomidescrumy/templates/ayomidescrumy/goal.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Goal</title>
</head>
<body>
    <div class="container">
        {% if request.user.is_authenticated %}
		<a style="float: right;" href="/ayomidescrumy/accounts/logout" class="btn btn-primary m-3">Log Out</a>
		{%else%}
		<a style="float: right;" href="/ayomidescrumy/accounts/login" class="btn btn-primary m-3">Log IN</a>
		{% endif %}
        <p class="badge badge-danger m-3"> {{request.user.username}} is logged in </p>
		<p class="badge badge-danger m-3">Group: {{request.user.groups.all.0}}</p>
		
        <h1>Add Goal</h1>
        <div class="row">
            <div class="col-md-4">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <span>Goal would be created for {{request.user.username}} in {{goal_status}}</span><br>
                <button type="submit" class="btn btn-primary mt-3">Add Goal</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

ayomidescrumy/templates/ayomidescrumy/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Home</title>
<style>
a{
	color:black
}
	table {
	  border-collapse: collapse;
	  width: 100%;
	}
	
	td, th {
	  border: 1px solid #110f0f;
	  text-align: left;
	  padding: 8px;
	}
	
	tr:nth-child(even) {
	  background-color: #d9dbec;
	}
</style>
</head>

<body>
    <div class="container">
		{% if request.user.is_authenticated %}
		<a style="float: right;" href="/ayomidescrumy/accounts/logout" class="btn btn-primary m-3">Log Out</a>
		{%else%}
		<a style="float: right;" href="/ayomidescrumy/accounts/login" class="btn btn-primary m-3">Log IN</a>
		{% endif %}
        
		<p class="badge badge-danger m-3"> {{request.user.username}} is logged in </p>
		<p class="badge badge-danger m-3">Group: {{request.user.groups.all.0}}</p>
		
        <a href="/ayomidescrumy/changegroup" class="btn btn-primary m-3">Change Group</a>
		{%if messages%}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">{{message}}</div>
        {%endfor%}
     {%endif %}
    <table style="width : 100%">
		<tr>
			<th>User</th>
			<th>Weekly Goals</th>
			<th>Daily Goals</th>
			<th>Verify Goals</th>
			<th>Done Goals</th>
		</tr>
		{% for user in users %}
		<tr>
			<td>{{user}}</td>
			<td>{% for goal in weekly %}
				{%if goal.user.username == user.username %}
				{% if request.user.groups.all.0 == developer and goal.user.username != request.user.username%}	
				<span>{{goal}} | {{goal.goal_id}} </span>
				{%else%}
				<a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>{{goal}}</a> | {{goal.goal_id}} <a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>| Move Goal</a>	
			{% endif %}<br>
				{%endif%}
				{%endfor%}

				


			</td>
			<td>
				{% for goal in daily%}
				{%if goal.user.username == user.username%}
				{% if request.user.groups.all.0 == developer and goal.user.username != request.user.username%}	
				<span>{{goal}} | {{goal.goal_id}} </span>
				{%else%}
				<a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>{{goal}}</a> | {{goal.goal_id}} <a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>| Move Goal</a>
				
				
			{% endif %}<br>{%endif%}
				{%endfor%}
			</td>

			<td>
				{% for goal in verify%}
				{%if goal.user.username == user.username %}
				
				{% if request.user.groups.all.0 == developer and goal.user.username != request.user.username%}	
				<span>{{goal}} | {{goal.goal_id}} </span>
				{%else%}
				<a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>{{goal}}</a> | {{goal.goal_id}} <a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>| Move Goal</a>
				
				
			{% endif %} <br>{%endif%}
				
				{%endfor%}
				
			</td>

			<td>
				{% for goal in done %}
				{%if goal.user.username == user.username %}
				
				{% if request.user.groups.all.0 == developer and goal.user.username != request.user.username%}	
				<span>{{goal}} | {{goal.goal_id}} </span>
				{%else%}
				<a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>{{goal}}</a> | {{goal.goal_id}} <a href={% url 'ayomidescrumy:movegoal' goal.goal_id %}>| Move Goal</a>
				
				
			{% endif %}<br>
				{%endif%}
				{%endfor%}
			</td>

		</tr>
		{%endfor%}
	</table>
    <br><br>
    <a href="{% url 'ayomidescrumy:addgoal' %}" class="btn btn-primary m-1">Add Goal</a>
   
    </div>

</body>

</html>

ayomidescrumy/templates/ayomidescrumy/index.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Index</title>
</head>


<body>
    <div class="container">
        
		<a style="float: right;" href="/ayomidescrumy/accounts/login" class="btn btn-primary m-3">Log IN</a>

    <h1>SIGN UP</h1>
    <div class="row">
        <div class="col-md-4">
            <form action="{% url 'ayomidescrumy:about' %}" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
        </div>
    </div>
    </div>
    
</body>
</html>

ayomidescrumy/templates/ayomidescrumy/moveGoal.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<title>Goal</title>
</head>
<body>
    <div class="container">
        {% if request.user.is_authenticated %}
		<a style="float: right;" href="/ayomidescrumy/accounts/logout" class="btn btn-primary m-3">Log Out</a>
		{%else%}
		<a style="float: right;" href="/ayomidescrumy/accounts/login" class="btn btn-primary m-3">Log IN</a>
		{% endif %}
        <p class="badge badge-danger m-3"> {{request.user.username}} is logged in </p>
		<p class="badge badge-danger m-3">Group: {{request.user.groups.all.0}}</p>
		<h1>Move Goal</h1>
        <div class="row">
            <div class="col-md-4">
                <h1 class="badge badge-primary">Goal Name: {{goal_name}}</h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>